services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rlt-testcase-bot
    env_file:
      - src/bot.env
      - src/db.env
    command: sh -c "python main.py"
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    depends_on:
      db:
        condition: service_started
  db:
    image: mongodb/mongodb-community-server:6.0-ubi8
    container_name: rlt-testcase-db
    ports:
      - "27017:27017"
    environment:
        MONGO_INITDB_ROOT_USERNAME: user
        MONGO_INITDB_ROOT_PASSWORD: pass
    volumes:
      - type: bind
        source: ./data
        target: /data/db
